# Generated by Django 4.2.7 on 2023-11-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("photo_url", models.CharField(max_length=200)),
                ("link_url", models.CharField(max_length=200)),
                ("c_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "chicken",
            },
        ),
    ]
